version: '3'
services:
  mysqldb:
    image: mysql:8.0
    container_name: easypan-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: easypan
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/easypan.sql:/docker-entrypoint-initdb.d/easypan.sql

  redisdb:
    image: redis:latest
    container_name: easypan-redis
    ports:
      - "6380:6379"

  backend:
    build: ./backend
    container_name: easypan-backend
    ports:
      - "7090:7090"
    depends_on:
      - mysqldb
      - redisdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/easypan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
      SPRING_REDIS_HOST: redisdb
      SPRING_REDIS_PORT: 6379
      PROJECT_FOLDER: /files

  frontend:
    build: ./frontend
    container_name: easypan-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
